approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@canopytax/*"
  - browserslist-config-canopy
  - canopy-webpack-config
  - eslint-config-canopy
  - kremling
  - single-spa
  - single-spa-canopy
